class AuthError(Exception):
    """Исключение при ошибке аутентификации"""
    pass
